apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: flat
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 11355
      targetPort: 11355
