apiVersion: v1
kind: Service
metadata:
  name: evaluator
  namespace: flat
  labels:
    app: evaluator
spec:
  selector:
    app: evaluator
  ports:
    - protocol: TCP
      port: 11355
      targetPort: 11355
