apiVersion: v1
kind: Service
metadata:
  name: aggregator
  namespace: flat
  labels:
    app: aggregator
spec:
  selector:
    app: aggregator
  ports:
    - protocol: TCP
      port: 11355
      targetPort: 11355
