
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasets-pv
  namespace: flat
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-path
  hostPath:
    path: /opt/onnx_fl/datasets
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-pvc
  namespace: flat
spec:
  volumeName: datasets-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasets-server-pv
  namespace: flat
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/onnx_fl/extra/datasets-server/server
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-server-pvc
  namespace: flat
spec:
  volumeName: datasets-server-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
